name: ✒️ Generate Documentation

on: [push, pull_request, workflow_dispatch]

jobs:

  Client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.6.1

    - name: Install Dependencies
      run: npm ci

    - name: Setup Git Config
      run: |
        git config user.name "GitHub Documentation Bot"
        git config user.email ""

    - name: Generate Documentation
      run: npx typedoc

    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Commit
      run: |
        git add --force docs 
        git commit -m "Generate Documentation"
        git push origin ${{ steps.vars.outputs.short_ref }}
