name: 🚀 Publish

on: workflow_dispatch
    
jobs:

  Publish:
    runs-on: ubuntu-latest 
    
    permissions: 
      contents: read
      packages: write 
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node for NPM Registry
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ming-suhi'
      
      - name: Publish to NPM Registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Setup Node for Github Registry
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ming-suhi'
          
      - name: Publish to Github Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
